### ISSUE TITLE
Is this project unmaintained?

### ISSUE THREAD

**Issue by stevenmaguire** [jadell/neo4jphp#168]
Is this project no longer maintained? There are a number of pull requests and issues with no response.

**Comment by jadell** [comment]
It's maintained when the maintainer has time. Is there a specific issue or pull request you want resolved?

**Comment by stevenmaguire** [comment]
Ah! Sorry for the test for life. I was curious about #166 and #167 but they are currently failing because of an unrelated memcached issue that is causing the build to fail. That memcached issue appears to affect a couple other issues. Do you have a preferred method to resolve the build issue?

**Comment by jadell** [comment]
I'll take a look at the memcached issue this week. If it's easy to solve, I'll fix it, unless you have a fix already. Either way, I'll take a look at and merge your pull requests, since they are unlikely to be related to the memcached issue.

**Comment by stevenmaguire** [comment]
Great. Thanks. I am happy to help after you take a look. Let me know.

**Comment by jadell** [comment]
Memcached on TravisCI fixed with d20365b6f23a8a9ac42e66b021180c6ac2c6de2a

Looking into other pull requests now.
