### ISSUE TITLE
Client not found..

### ISSUE THREAD

**Issue by JugalSA** [jadell/neo4jphp#185]
Hey, I have put the project in my library folder.

Structure is like this..

\libraries\neo4jphp\lib\Everyman\Neo4j\Client.php
Code ::
$client = new Everyman\Neo4j\Client('localhost', 7474);
 print_r($client->getServerInfo());
exit;

But i am not able to set up this..
Please also tell the use of autoload.php as I am not seeing this in the project folder..

**Comment by jadell** [comment]
Have you tried installing the library using Composer? That's the supported way to do it. Otherwise, you'll have to write your own autoloader, or manually include/require each class file.

**Comment by JugalSA** [comment]
Got it..Thanks..
